Play at modifying byte code for testing purposes with ByteBuddy.
- The version 1.8.10 of Byte Buddy is the later one before causing a ClassNotFoundException.
  java.lang.NoClassDefFoundError: net/bytebuddy/jar/asm/commons/SignatureRemapper

References:
- [A Guide to Byte Buddy](https://www.baeldung.com/byte-buddy)