It should fail to prepare stdin to read a file.
- Use ByteBuddy instead of Powermock to change the Files::lines method behaviour.
  Indeed no PowermockExtension exists for JUnit Jupiter.
- It still fails because of what follows.
  java.lang.IllegalStateException: The Byte Buddy agent is not installed or not accessible
  Caused by: java.lang.reflect.InvocationTargetException
  Caused by: java.lang.IllegalStateException: The Byte Buddy agent is not loaded or this method is not called via the system class loader