It should fail to prepare stdin to read a file.
- Install the ByteBuddy agent before modifying the byte code of an already loaded class.
- It still fails because of what follows.
  java.lang.NoClassDefFoundError: net/bytebuddy/jar/asm/commons/SignatureRemapper
  Caused by: java.lang.ClassNotFoundException: net.bytebuddy.jar.asm.commons.SignatureRemapper
- Fix dependencies by adding the byte-buddy-agent as a dependency.